apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  namespace: test-notation
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: 844333597536.dkr.ecr.us-west-2.amazonaws.com/kyverno-demo:v1
  initContainers:
  - name: init-myservice
    image: busybox:1.28
  - name: init-mydb
    image: busybox:1.28