apiVersion: notation.nirmata.io/v1alpha1
kind: TrustStore
metadata:
  name: aws-signer-ts
spec:
  trustStoreName: aws-signer-ts
  type: signingAuthority
  caBundle: |-
    -----BEGIN CERTIFICATE-----
    MIICWTCCAd6gAwIBAgIRAL03YHNvqGFX2RlWNG5QKE4wCgYIKoZIzj0EAwMwbDEL
    MAkGA1UEBhMCVVMxDDAKBgNVBAoMA0FXUzEVMBMGA1UECwwMQ3J5cHRvZ3JhcGh5
    MQswCQYDVQQIDAJXQTErMCkGA1UEAwwiQVdTIFNpZ25lciBDb2RlIFNpZ25pbmcg
    Um9vdCBDQSBHMTAgFw0yMjAzMTcxODAwMDZaGA8yMTIyMDMxNzE5MDAwNlowbDEL
    MAkGA1UEBhMCVVMxDDAKBgNVBAoMA0FXUzEVMBMGA1UECwwMQ3J5cHRvZ3JhcGh5
    MQswCQYDVQQIDAJXQTErMCkGA1UEAwwiQVdTIFNpZ25lciBDb2RlIFNpZ25pbmcg
    Um9vdCBDQSBHMTB2MBAGByqGSM49AgEGBSuBBAAiA2IABEYunZoWAX7G6A0r6hsu
    toY8dHHbK5KKgAQ9WoJqXxASleJBRoU1eRLng8IzE2wuFym4i+sLb/HdrakBgVpt
    hrLyDxYKoNPChSQ1Mq474oLxDQ45YjDhLoUn1ZUMZKguDqNCMEAwDwYDVR0TAQH/
    BAUwAwEB/zAdBgNVHQ4EFgQUvTV2eZB8DU9XGyNIvtU4FxXCLzgwDgYDVR0PAQH/
    BAQDAgGGMAoGCCqGSM49BAMDA2kAMGYCMQCqFVLTMGclG0p0zM/N0dLuK2E7kveb
    QGQQbWx2AbO1yNEL9PxUFFByFST2sSD8QrsCMQCQGLqKW/MQg4ucadoVlmH4Y3zc
    syRlsDoYP/SChe/2Ish1/9HvWUQtBeQxBU3Q5Jw=
    -----END CERTIFICATE-----