apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kyverno-notation-aws
  name: kyverno-notation-aws
  namespace: kyverno-notation-aws
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kyverno-notation-aws
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kyverno-notation-aws
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - image: ghcr.io/vishal-chdhry/kyverno-notation-aws:v1-rc3
        imagePullPolicy: Always
        name: kyverno-notation-aws
        # args:
        # - --debug
        # USE IF IRSA IS NOT CONFIGURED
        # - --imagePullSecrets=regcred
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 32Mi
            cpu: 100m
        securityContext:
          runAsUser: 2000
          runAsGroup: 3000
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        env:
        - name: NOTATION_DIR
          value: /notation
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace  
        # USE IF IRSA IS NOT CONFIGURED
        # - name: AWS_ACCESS_KEY_ID
        #   value: ${AWS_ACCESS_KEY_ID}
        # - name: AWS_SECRET_ACCESS_KEY
        #   value: ${AWS_SECRET_ACCESS_KEY}
        - name: AWS_REGION
          value: us-west-2
        volumeMounts:
          - name: notation
            mountPath: /notation
          - name: certs
            mountPath: /certs
      - image: ghcr.io/nirmata/kube-notation:v1-alpha1
        imagePullPolicy: Always
        name: kube-notation
        env:
        - name: NOTATION_DIR
          value: /notation
        securityContext:
          runAsUser: 2000
          runAsGroup: 3000
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL          
        resources:
          limits:
            memory: 512Mi
          requests:
            memory: 32Mi
            cpu: 100m
        volumeMounts:
          - name: notation
            mountPath: /notation            
      volumes:
        - name: notation
          emptyDir: {}
        - name: certs
          secret:
            defaultMode: 420
            secretName: kyverno-notation-aws-tls
      serviceAccountName: kyverno-notation-aws